### ISSUE TITLE
Internal server error when signing in?

### ISSUE THREAD

**Issue by WilliamMayor** [fief-dev/fief#100]
## Describe the bug

I get an internal server error when I try to sign in after opening an auth url that has been set up to show the register screen first.

## To Reproduce

I created a auth url using the flask integration and the following code:

```
redirect_uri = url_for("signup_callback", _external=True)
auth_url = fief.auth_url(
    redirect_uri,
    scope=["openid"],
    extras_params={"screen": "register"},
)
return redirect(auth_url)
```

When opening that page I then navigated to the sign in page and tried to sign in. I got an internal server error page.

I can sign in using this account if I create the auth_url without the extras_params bit so I think it's something to do with that?

## Expected behavior

I expected to be signed in and redirected to my app.

## Configuration

* Cloud

**Comment by frankie567** [comment]
Hi @WilliamMayor 👋 

Does it *always* happen or does it happen from time to time?

If it's the second option, it's because we sometimes experience random errors with our cloud database which causes some requests to fail. We're probably a bit light on RAM... I think I'll have to upgrade to a bigger instance 💸

**Comment by mfruhner** [comment]
Hey, I am also experiencing this right now with almost all requests. Worked fine yesterday evening.
Would you recommend setting up a local deployment ?

**Comment by frankie567** [comment]
@mfruhner Sorry for the disturbance! I've tweaked the servers configuration so it shouldn't happen anymore.
