### ISSUE TITLE
Missing translation keys for "Adresse e-mail" and "Mot de passe"

### ISSUE THREAD

**Issue by michaldev** [fief-dev/fief#130]
Hi. Thank you for update with translations.  I see, that something is wrong with 2 messages.

"Adresse e-mail" and  "Mot de passe". I see this words on login/register page, but I not found it on poeditor.

<img width="1552" alt="Zrzut ekranu 2022-12-26 o 16 09 29" src="https://user-images.githubusercontent.com/5132385/209562244-4fc64f19-3b1e-44ac-933b-341adabbe5c0.png">

**Comment by frankie567** [comment]
After testing, it seems there is some kind of weird cache happening on forms translations. I'll look into this!
