### ISSUE TITLE
Permission from roles are not applied to users with role 

### ISSUE THREAD

**Issue by filipagh** [fief-dev/fief#154]
## Describe the bug
user with role with some permission does not pass authentication which request that permission

we can create roles and add permissions to it 
then we can add role to user

so we expect that user has that permissions  

## To Reproduce

1. have role with permission , and assign that role to user 
![image](https://user-images.githubusercontent.com/22474494/224391640-513e2ea9-26bf-4911-8a2b-984afdc24600.png)
![image](https://user-images.githubusercontent.com/22474494/224391701-e5b282ba-1fda-41ad-a397-b43f3fbe32ca.png)

3. Click on user permissions you will see no permissions 
![image](https://user-images.githubusercontent.com/22474494/224391806-0d62da57-eef5-42fc-b94f-87a2c43212d2.png)
5. try authentication with permission  -> result in forbidden

BUT
1. add permission to user explicitly 
![image](https://user-images.githubusercontent.com/22474494/224392048-b6a80331-ca22-4d92-99a8-3312e0879863.png)
2. auth now pass 

## Expected behavior
add permission from roles to users with its roles 

## Configuration

* Cloud or self-hosted: Cloud

## Additional context

no

**Comment by frankie567** [comment]
Yes, normally it works ; but I've started to see errors popping on our cloud hosting ; which causes this side effect. I'm on it!

**Comment by frankie567** [comment]
Shall be fixed with latest release! (deployed on Fief Cloud)

Thank you for the report 🙏
