### ISSUE TITLE
custom email (SMTP) not working

### ISSUE THREAD

**Issue by JustinGuese** [fief-dev/fief#271]
## Describe the bug

SMTP custom emails don't work, at least not for ZOHO emails

## To Reproduce

1. Set email provider to custom

```
EMAIL_PROVIDER=SMTP
EMAIL_PROVIDER_PARAMS={"host": "smtppro.zoho.eu", "username": "xxxx", "password": "ZohoAppPassword", "port": 465, "ssl" : "True"}
```

2. Wait ~1 Minute
3. Timeout shows in logs

## Expected behavior

Email is sent

## Configuration

* Cloud or self-hosted: self-hosted
* If self-hosted, Fief version: latest

## Additional context

I bet you are not setting a secure connection and just use the default python smtp? This does not work anymore with current email providers (since ~2000)

**Comment by JustinGuese** [comment]
When I am using the same combinations with smtplib (the secure connection mode), it works. When using the default smtplib it does not work since that was switched off by most email providers a long time ago

**Comment by JustinGuese** [comment]
yes that was indeed the problem, created a PR

**Comment by frankie567** [comment]
Our implementation of SMTP supports TLS, which is most likely over port `587` on your provider.

Actually, we already gave a specific solution for Zoho: https://github.com/orgs/fief-dev/discussions/234#discussioncomment-6374491
