### ISSUE TITLE
Check password strength in Quickstart CLI

### ISSUE THREAD

**Issue by frankie567** [fief-dev/fief#305]
### Discussed in https://github.com/orgs/fief-dev/discussions/304

<div type='discussions-op-text'>

<sup>Originally posted by **otailai** November 24, 2023</sup>
Here are my operation steps:

1. run command docker run -it --rm ghcr.io/fief-dev/fief:latest fief quickstart --docker,  and then, I typed my email and password, after that, I got reponse in command line as following:
`docker run \
  --name fief-server \
  -p 8000:8000 \
  -d \
  -e "SECRET=XXX" \
  -e "FIEF_CLIENT_ID=XXX" \
  -e "FIEF_CLIENT_SECRET=XXX" \
  -e "ENCRYPTION_KEY=XXX" \
  -e "PORT=8000" \
  -e "ROOT_DOMAIN=localhost:8000" \
  -e "FIEF_DOMAIN=localhost:8000" \
  -e "FIEF_MAIN_USER_EMAIL=anne@bretagne.duchy" \
  -e "FIEF_MAIN_USER_PASSWORD=XXX" \
  -e "CSRF_COOKIE_SECURE=False" \
  -e "SESSION_DATA_COOKIE_SECURE=False" \
  -e "USER_LOCALE_COOKIE_SECURE=False" \
  -e "LOGIN_SESSION_COOKIE_SECURE=False" \
  -e "SESSION_COOKIE_SECURE=False" \
  -e "FIEF_ADMIN_SESSION_COOKIE_SECURE=False" \
  ghcr.io/fief-dev/fief:latest
`
2.  I execute the docker command above, the feedback is good, the container is running:
<img width="1406" alt="image" src="https://github.com/fief-dev/fief/assets/10295363/76aa50f1-0a22-48ef-af0d-55e341756319">

Unfortunately, when I open the login page(http://localhost:8000/admin) in browser, something went run
<img width="960" alt="image" src="https://github.com/fief-dev/fief/assets/10295363/e680eefa-089f-4912-917f-9fff87afbc57">

So, I start to check the logs, found my password was too weak.
<img width="1384" alt="image" src="https://github.com/fief-dev/fief/assets/10295363/e86ba4dc-bf36-47d4-84dd-811ede6348ff">

After re-running the docker start command, I get the correct feedback.

My confusion is that maybe we can enhance the password inputing part, so our users won't debug anymore when they have such problems. 

Thank you. 
 
</div>

**Comment by otailai** [comment]
good to know that, I am considering to use fief now, maybe one day I could be a commiter :)

**Comment by ScottFred** [comment]
@frankie567   I just submitted a PR for this one.  Let me know what you think.  Thanks
