### ISSUE TITLE
Internal Server Error in sign up with custom user fields

### ISSUE THREAD

**Issue by paolodina** [fief-dev/fief#31]
## Describe the bug
Internal Server Error is returned submitting the registration form as described below.

## To Reproduce
1. create custom user fields like this
![image](https://user-images.githubusercontent.com/1157401/172275500-ed22df96-c230-40a4-8af3-eeb61e5761a1.png)
2. create `index.html` and `callback.html` as described here https://docs.fief.dev/integrate/javascript/browser/
3. start a the web server and go to [http://localhost:8000/](http://localhost:8000/) supposing `index.html` is served there
4. click on Sign up
5. fill email address and password
6. **don't check** the "terms" checkbox
7. submit the form

## Expected behavior
1. frontend: data validation, prevent the submit
2. backend: don't crash, return HTTP 400/422

## Configuration

* Cloud or self-hosted: Cloud

**Comment by frankie567** [comment]
Thank you for the detailed report @paolodina, I'll investigate right away!

**Comment by frankie567** [comment]
Fixed! I'll make a release today to push it live!

@all-contributors add @paolodina for bug
