### ISSUE TITLE
Override auth pages templates

### ISSUE THREAD

**Issue by frankie567** [fief-dev/fief#352]
To provide better customization, we could offer to override HTML templates using a defined location. This is handled pretty well by Jinja.

In a Docker environment, developers would only need to mount their templates to the required location, which is very neat.

---

If it works well, this approach could be expanded to email templates as well.

**Comment by gokturkDev** [comment]
This is a must! As a startup, we would love to use Fief but unfortunately the generic pages really hurt the brand image. I believe there are many out there like us. Is there any timeline for this?

Thanks 🙌

**Comment by frankie567** [comment]
Thank you for your feedback, @gokturkDev 👍  Unfortunately, I don't have any timeline for this at the moment.

For the record, you can already customize logo, fonts and colors of the login; which should already allow you to look like very close to your branding: https://docs.fief.dev/configure/customization/themes/

**Comment by gokturkDev** [comment]
Hi yes this is a great step forward but we have custom animations, validation logic etc. that requires a more fine grained control. 

If you could point to me how the auth pages are stored, I may be able to hack something together. No promises though

**Comment by AmeerArsala** [comment]
Same exact situation here. Please keep me updated! I want to make my own custom login pages and use Fief as a sort of 'backend' if you will and then have an admin dashboard generated by fief

**Comment by drexhacker** [comment]
On this  also

**Comment by frankie567** [comment]
Released in Stronghold,  the **private edition** of Fief, accessible to our paid backers, which includes exclusive features.

https://docs.fief.dev/stronghold/#override-authentication-page-templates
