### ISSUE TITLE
fief.services.email.base.SendEmailError: STARTTLS extension not supported by server.

### ISSUE THREAD

**Issue by cfredericksen** [fief-dev/fief#391]
## Describe the bug

I want to send email to my local smtp server. Everything works great except it appears "ssl": "false" is ignored or something. I have other apps using my simple, plaintext, internal-only smtp server just fine. 

```
            - name: EMAIL_PROVIDER
              value: "SMTP"
            - name: EMAIL_PROVIDER_PARAMS
              value: '{"host": "192.168.200.7", "username": "chad", "password": "(redacted}", "port": "2525", "ssl": "false"}'
```

## Expected behavior

I see the the fief-worker pod connect to my SMTP pod but fief-worker throws an error. "fief.services.email.base.SendEmailError: STARTTLS extension not supported by server."

## Configuration

* If self-hosted, Fief version: 0.28.6

## Additional context
Love the project, works amazing with my custom app.

**Comment by frankie567** [comment]
I think the issue comes from the `ssl` property: you set it to the string `"false"`, which probably evaluates to a truthy value in the email provider logic. Try like this with a plain boolean:

```
            - name: EMAIL_PROVIDER
              value: "SMTP"
            - name: EMAIL_PROVIDER_PARAMS
              value: '{"host": "192.168.200.7", "username": "chad", "password": "(redacted}", "port": "2525", "ssl": false}'
```

**Comment by cfredericksen** [comment]
I think I stared at the computer for too long. That was it. Thank you.
