### ISSUE TITLE
Redirect to user dashboard if no login session after a successfull password reset

### ISSUE THREAD

**Issue by frankie567** [fief-dev/fief#400]
Discussion: https://github.com/orgs/fief-dev/discussions/392

**Comment by ApprenticeofEnder** [comment]
Does this still need someone to have a look at it?

**Comment by frankie567** [comment]
Yes, this is not yet fixed. The fix should be quite straightforward. Here is the part of the code needing changes: https://github.com/fief-dev/fief/blob/9c7e72e4d37c078c722a5445bc12a6c1e159b274/fief/apps/auth/routers/reset.py#L96-L100

**Comment by ApprenticeofEnder** [comment]
Turns out, yeah, it was fairly straightforward. Not 100% sure on the redirection target, but other than that, should be good to go.
