### ISSUE TITLE
"Create an access token" is broken

### ISSUE THREAD

**Issue by realchandan** [fief-dev/fief#492]
In the admin dashboard, I'm unable to create an access token for a user because the "Client" dropdown doesn't show any clients.

I remember this wasn't an issue in earlier versions (since I've used this feature before). I recently updated Fief to v0.29.1, and to confirm my theory, I downgraded it to v0.28.9, but the dropdown still showed no clients.

I downgraded even further to v0.28.2, and now the clients started showing up in the dropdown.

I tried both Firefox and Chrome to test this.

**Comment by frankie567** [comment]
Thank you for reporting, that was a nasty JS bug.
