### ISSUE TITLE
invalid grant server v 0.29

### ISSUE THREAD

**Issue by JustinGuese** [fief-dev/fief#493]
Hi, this was reported by some other users as well
https://github.com/orgs/fief-dev/discussions/231

What happens?

The server returns an invalid grant with v0.29, v0.28 works.

Reproduction:

1. Docker/Kubernetes deployment of image: ghcr.io/fief-dev/fief:0.29
2. FastAPI template in docs
3. FiefRequestError: [400] - {"error":"invalid_grant"}

Fix:

Use v 0.28
image: ghcr.io/fief-dev/fief:0.28

**Comment by frankie567** [comment]
Did you pull the latest image, version 0.29.1. This looks like the bug we fixed in #469.
