### ISSUE TITLE
docker exec

### ISSUE THREAD

**Issue by ScrimForever** [fief-dev/fief#7]
## Describe the bug

pydantic.error_wrappers.ValidationError: 1 validation error for Settings
fief_client_id
  field required (type=value_error.missing)

## To Reproduce

1. docker run --name fief-server -p 8000:8000 -d -e "SECRET=qgPj0aESg2JJMXzsykxI2zLMycd0yiehJn8PpXcL78NfwdCx31VRStu_pwlzEl4B0_CYmQwbmlwFS4p4xKoAtw" -e "FIEF_CLIENT_SECRET=XYQdiF_mPEfyc6L3noelZoHptVZ-aCu1lNhk_N77OYs"  -e "ENCRYPTION_KEY=YmNSWgnMNepamUSXkxrN2C9YNs9BgCy1UHJzsKRXcWc=" ghcr.io/fief-dev/fief:latest
8369d8594b45209ef240f967215efb025891521236ebc5f9bb0bc21681f6c692
2. docker exec fief-server fief workspaces create-main

## Configuration

* If self-hosted, Fief version:

![image](https://user-images.githubusercontent.com/5040124/164944472-09ea37f9-ee77-4283-980f-18e2a2569274.png)

**Comment by frankie567** [comment]
Hello @ScrimForever! Welcome to Fief!

You missed one required environment variable, `FIEF_CLIENT_ID`, hence the error shown.

If you used the [quickstart command](https://docs.fief.dev/self-hosting/quickstart/#quickstart), you should have obtained a command with all the required variables:

```bash
docker run \
  --name fief-server \
  -p 8000:8000
  -d \
  -e "SECRET=XXX" \
  -e "FIEF_CLIENT_ID=XXX" \
  -e "FIEF_CLIENT_SECRET=XXX" \
  -e "ENCRYPTION_KEY=XXX" \
  ghcr.io/fief-dev/fief:latest
```

PS: You should avoid to share your SECRET, ENCRYPTION_KEY and CLIENT_SECRET values: those are sensitive variables that should be kept absolutely private.
